name : Deploy

on :
  push:
    branches:
      - main 

jobs:
  Deploy:
    name : "Deploy the Docker File"
    runs-on : ubuntu-latest

    steps:
      - name : "Build the Docker Image"
        uses : actions/checkout@v4

      - name : "Docker Login"
        uses : docker/login-action@v3

        with:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t samdocker4/fashion-recommendation-system:latest .
    
      - name: Push Docker Image
        run : docker push samdocker4/fashion-recommendation-system:latest