name : Test_cases and Pipline

on :
  pull_request :
    branches:
      - main

jobs:
  run-tests :
    name : "Run all tests pipline "
    runs-on : ubuntu-latest

    
    steps:

      - name : "check-out code"
        uses : actions/checkout@v3

      - name : "Setup Python 3.11"
        uses : actions/setup-python@v4
        with:
          python-version: '3.11'

      - name : "Install dependencies"
        run : pip install -r requirements.txt

      - name : "Run all test and the pipline"
        env :
          MLFLOW_TRACKING_USERNAME : ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD : ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run : pytest tests/test_pipline.py -v 

      - name : "Test Case and Pipline Passed"
        run : echo "All test case and Pipline passesd"


  